use axum::{
    extract::Path,
    http::{StatusCode, header},
    response::{IntoResponse, Response},
};

// Embed all static assets at compile time for single-binary deployment
const FILES: &[(&str, &str)] = &[
    ("css/app.css", include_str!("../../static/css/app.css")),
    // Served from under `/static/` rather than the root because that prefix is
    // already skipped by the session, CSRF and forward-auth layers, so the
    // response is guaranteed cookie-free — a `Set-Cookie` on a `public,
    // immutable` response is a shared-cache hazard. `start_url`/`scope` inside
    // it are absolute for the same reason: they resolve against the manifest's
    // own URL, and a relative value here would scope the app to `/static/`.
    (
        "manifest.webmanifest",
        include_str!("../../static/manifest.webmanifest"),
    ),
    ("js/app.js", include_str!("../../static/js/app.js")),
    (
        "js/behaviors.js",
        include_str!("../../static/js/behaviors.js"),
    ),
    ("js/admin.js", include_str!("../../static/js/admin.js")),
    ("js/csrf.js", include_str!("../../static/js/csrf.js")),
    ("js/login.js", include_str!("../../static/js/login.js")),
    ("js/passkey.js", include_str!("../../static/js/passkey.js")),
    ("js/offline.js", include_str!("../../static/js/offline.js")),
    ("js/pwa.js", include_str!("../../static/js/pwa.js")),
    ("js/setup.js", include_str!("../../static/js/setup.js")),
    ("js/search.js", include_str!("../../static/js/search.js")),
    (
        "js/statistics.js",
        include_str!("../../static/js/statistics.js"),
    ),
    (
        "js/summarizer.js",
        include_str!("../../static/js/summarizer.js"),
    ),
    ("js/utils.js", include_str!("../../static/js/utils.js")),
    (
        "js/components/rdrs-flash.js",
        include_str!("../../static/js/components/rdrs-flash.js"),
    ),
    (
        "js/components/rdrs-kb-help.js",
        include_str!("../../static/js/components/rdrs-kb-help.js"),
    ),
    (
        "js/components/rdrs-sidebar.js",
        include_str!("../../static/js/components/rdrs-sidebar.js"),
    ),
];

// Self-hosted webfonts (latin subset). Binary, so embedded via `include_bytes!`
// and served ahead of the text `FILES` table. Vendored to avoid a Google Fonts
// CDN dependency (privacy for self-hosted deployments); SIL OFL licensed, see
// static/fonts/OFL-*.txt.
const FONTS: &[(&str, &[u8])] = &[
    (
        "fonts/newsreader-latin.woff2",
        include_bytes!("../../static/fonts/newsreader-latin.woff2"),
    ),
    (
        "fonts/newsreader-italic-latin.woff2",
        include_bytes!("../../static/fonts/newsreader-italic-latin.woff2"),
    ),
    (
        "fonts/archivo-latin.woff2",
        include_bytes!("../../static/fonts/archivo-latin.woff2"),
    ),
    (
        "fonts/ibm-plex-mono-400-latin.woff2",
        include_bytes!("../../static/fonts/ibm-plex-mono-400-latin.woff2"),
    ),
    (
        "fonts/ibm-plex-mono-500-latin.woff2",
        include_bytes!("../../static/fonts/ibm-plex-mono-500-latin.woff2"),
    ),
    (
        "fonts/ibm-plex-mono-600-latin.woff2",
        include_bytes!("../../static/fonts/ibm-plex-mono-600-latin.woff2"),
    ),
    (
        "fonts/noto-sans-symbols2-stars.woff2",
        include_bytes!("../../static/fonts/noto-sans-symbols2-stars.woff2"),
    ),
];

// Home-screen icons named by the web app manifest. Generated by `build.rs` from
// the same `favicon.svg` as the favicons and picked up out of `OUT_DIR`, so they
// cannot drift from the icon in the browser tab. They are served from here
// rather than alongside the favicons in `handlers::favicon` for the same reason
// the manifest is: a root-level `/icon-192.png` would need its own entry in
// three separate middleware skip lists before it was safe to cache publicly.
const ICONS: &[(&str, &[u8])] = &[
    (
        "icons/icon-192.png",
        include_bytes!(concat!(env!("OUT_DIR"), "/icon-192.png")),
    ),
    (
        "icons/icon-512.png",
        include_bytes!(concat!(env!("OUT_DIR"), "/icon-512.png")),
    ),
    (
        "icons/maskable-icon-512.png",
        include_bytes!(concat!(env!("OUT_DIR"), "/maskable-icon-512.png")),
    ),
];

/// The service-worker script, served from the site root by [`service_worker`].
///
/// Deliberately absent from [`FILES`]: a worker's default scope is the directory
/// it was served from, so at `/static/js/sw.js` it could not see the navigations
/// it exists to catch, and the two URLs would also need different
/// `Cache-Control` — see [`service_worker`].
const SERVICE_WORKER: &str = include_str!("../../static/js/sw.js");

/// Token embedded in the source of any static module that imports another
/// static module (e.g. `import … from './utils.js?v=__RDRS_ASSET_VERSION__'`).
/// It is substituted at serve time with the current build version so the nested
/// import resolves to a `?v=`-stamped URL, exactly like the top-level `<script>`
/// tags in the templates. Without it, ES-module imports request bare,
/// unversioned URLs that never change and so are cached forever under the
/// `immutable` header — a stale `utils.js` then silently breaks every module
/// that imports it (the `debounce` regression).
const ASSET_VERSION_PLACEHOLDER: &str = "__RDRS_ASSET_VERSION__";

/// Token in the service-worker source that carries [`worker_may_cache_static`]'s
/// answer into the script, substituted with `"true"` or `"false"` at serve time.
const STATIC_CACHE_PLACEHOLDER: &str = "__RDRS_CACHE_STATIC__";

/// Whether the service worker may keep `/static/` responses in the Cache API.
///
/// Derived from [`cache_control_for`] rather than from `GIT_VERSION` directly,
/// because it is the *same* decision and two copies of one rule drift. That
/// function drops to `no-cache` for a build from a dirty working tree: the
/// version suffix is identical across consecutive edits, so the `?v=` URL — and
/// so any cache keyed by it — cannot tell one build from the next. The Cache API
/// ignores `Cache-Control` entirely, so the worker has to be told separately or
/// it would serve the stale copy back and undo the escape hatch.
fn worker_may_cache_static() -> bool {
    cache_control_for() != "no-cache"
}

fn content_type_for(path: &str) -> &'static str {
    match std::path::Path::new(path)
        .extension()
        .and_then(|ext| ext.to_str())
    {
        Some("css") => "text/css; charset=utf-8",
        Some("woff2") => "font/woff2",
        Some("png") => "image/png",
        // The fall-through below is `application/javascript`, and every response
        // carries `X-Content-Type-Options: nosniff` — a manifest served as
        // JavaScript is not merely mislabelled, the browser refuses it outright
        // and the app silently stops being installable.
        Some("webmanifest") => "application/manifest+json",
        _ => "application/javascript",
    }
}

/// Shared with `handlers::favicon`, which embeds its images the same way and
/// so has exactly the same invalidation problem across an upgrade.
pub(crate) fn cache_control_for() -> &'static str {
    // `?v=…-dirty` URLs are emitted from a working tree with uncommitted
    // changes; the suffix is identical across consecutive dev edits, so
    // browsers would serve a stale cached copy under the long-lived immutable
    // header. Switch to `no-cache` for that case so dev iteration sees fresh
    // assets without a hard refresh.
    if crate::GIT_VERSION.ends_with("-dirty") {
        "no-cache"
    } else {
        "public, max-age=31536000, immutable"
    }
}

/// `GET /sw.js` — the service-worker script.
///
/// Served from the root so its registration scope is the whole site, and marked
/// `no-cache` rather than sharing [`cache_control_for`]'s year-long `immutable`.
/// The URL carries no `?v=` stamp on purpose (a stamped one would register a
/// *new* worker each deploy instead of updating the existing one), so it is the
/// only asset here whose content changes under a fixed URL — the one shape
/// `immutable` must never be applied to. Browsers already bypass their own cache
/// for a worker script; `no-cache` extends that to any proxy in between.
pub async fn service_worker() -> Response {
    (
        StatusCode::OK,
        [
            (header::CONTENT_TYPE, "application/javascript"),
            (header::CACHE_CONTROL, "no-cache"),
        ],
        SERVICE_WORKER
            .replace(ASSET_VERSION_PLACEHOLDER, crate::GIT_VERSION)
            .replace(
                STATIC_CACHE_PLACEHOLDER,
                if worker_may_cache_static() {
                    "true"
                } else {
                    "false"
                },
            ),
    )
        .into_response()
}

pub async fn serve(Path(path): Path<String>) -> Response {
    if let Some((name, bytes)) = FONTS.iter().chain(ICONS).find(|(name, _)| *name == path) {
        return (
            StatusCode::OK,
            [
                (header::CONTENT_TYPE, content_type_for(name)),
                (header::CACHE_CONTROL, cache_control_for()),
            ],
            *bytes,
        )
            .into_response();
    }
    match FILES.iter().find(|(name, _)| *name == path) {
        Some((name, content)) => (
            StatusCode::OK,
            [
                (header::CONTENT_TYPE, content_type_for(name)),
                (header::CACHE_CONTROL, cache_control_for()),
            ],
            // Stamp nested-import URLs with the build version so they cache-bust
            // across deploys. No-op for assets without the placeholder.
            content.replace(ASSET_VERSION_PLACEHOLDER, crate::GIT_VERSION),
        )
            .into_response(),
        None => StatusCode::NOT_FOUND.into_response(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every `/static/…` URL literal in `source`, with any `?v=` stamp dropped,
    /// as a serve-table key (i.e. minus the `/static/` prefix).
    ///
    /// Same crude scan as `every_template_referenced_script_is_served` below and
    /// for the same reason: the serve tables are hand-written allowlists, so the
    /// only way a reference and its entry stay in step is a test that reads the
    /// references back out of the source that makes them.
    /// The bare prefix on its own (`startsWith('/static/')`, or prose about it)
    /// yields an empty name and is dropped: it references no asset.
    fn static_urls_in(source: &str) -> Vec<String> {
        source
            .match_indices("/static/")
            .map(|(i, _)| {
                source[i + "/static/".len()..]
                    .chars()
                    .take_while(|c| !matches!(c, '"' | '\'' | '`' | '?' | ' ' | '>' | '\n'))
                    .collect::<String>()
            })
            .filter(|name: &String| !name.is_empty())
            .collect()
    }

    fn is_servable(name: &str) -> bool {
        FILES.iter().any(|(n, _)| *n == name) || FONTS.iter().chain(ICONS).any(|(n, _)| *n == name)
    }

    async fn body_of(path: &str) -> String {
        let resp = serve(Path(path.to_string())).await;
        let bytes = axum::body::to_bytes(resp.into_response().into_body(), usize::MAX)
            .await
            .unwrap();
        String::from_utf8(bytes.to_vec()).unwrap()
    }

    /// Nested ES-module imports resolve to bare URLs (`/static/js/utils.js`)
    /// that carry no `?v=` cache-buster, so under the 1-year `immutable` header
    /// a browser keeps a stale copy across deploys — the exact trap that broke
    /// `app.js`'s `debounce` import. Every importer of `utils.js` must request a
    /// version-stamped URL so a new release invalidates the cache.
    #[tokio::test]
    async fn js_nested_imports_are_version_busted() {
        let expected = format!("utils.js?v={}", crate::GIT_VERSION);
        for path in [
            "js/app.js",
            "js/components/rdrs-sidebar.js",
            "js/passkey.js",
        ] {
            let body = body_of(path).await;
            assert!(
                !body.contains(ASSET_VERSION_PLACEHOLDER),
                "{path}: placeholder was not substituted"
            );
            assert!(
                body.contains(&expected),
                "{path}: expected a version-stamped utils.js import ({expected})"
            );
            assert!(
                !body.contains("utils.js'") && !body.contains("utils.js\""),
                "{path}: still imports utils.js without a ?v= cache-buster"
            );
        }
    }

    /// Every `/static/js/*.js` a template references must be registered in
    /// `FILES`, or the browser gets a 404 for it. Assets are embedded by an
    /// explicit list here, so adding a `<script src>` to a template without a
    /// matching `FILES` entry silently ships a broken page — e.g. an unregistered
    /// `csrf.js` 404s, `window.fetch` is never patched, and every token-bearing
    /// POST starts failing. This walks the templates and fails on any referenced
    /// script the serve table cannot satisfy.
    #[tokio::test]
    async fn every_template_referenced_script_is_served() {
        let root = concat!(env!("CARGO_MANIFEST_DIR"), "/templates");
        let mut stack = vec![std::path::PathBuf::from(root)];
        let mut refs: Vec<String> = Vec::new();
        while let Some(dir) = stack.pop() {
            for entry in std::fs::read_dir(&dir).unwrap() {
                let path = entry.unwrap().path();
                if path.is_dir() {
                    stack.push(path);
                    continue;
                }
                let html = std::fs::read_to_string(&path).unwrap();
                for (i, _) in html.match_indices("/static/js/") {
                    let tail = &html[i + "/static/".len()..];
                    let name: String = tail
                        .chars()
                        .take_while(|c| !matches!(c, '"' | '\'' | '?' | ' ' | '>' | '\n'))
                        .collect();
                    if std::path::Path::new(&name)
                        .extension()
                        .and_then(|e| e.to_str())
                        == Some("js")
                    {
                        refs.push(name);
                    }
                }
            }
        }
        assert!(
            refs.iter().any(|r| r == "js/csrf.js"),
            "sanity: expected to find at least the csrf.js reference while scanning templates"
        );
        for name in &refs {
            assert!(
                FILES.iter().any(|(n, _)| n == name),
                "template references /static/{name} but it is not registered in FILES (404)"
            );
        }
    }

    /// The worker's precache is an `addAll`, which is all-or-nothing: one 404 in
    /// the list and `install` rejects, no cache is written, and the offline page
    /// the whole feature exists for is silently never there. Nothing else would
    /// notice — registration failures are swallowed by design.
    #[test]
    fn service_worker_only_names_servable_static_urls() {
        let referenced = static_urls_in(SERVICE_WORKER);
        assert!(
            !referenced.is_empty(),
            "sanity: the worker is expected to name at least one static asset"
        );
        for name in &referenced {
            assert!(
                is_servable(name),
                "sw.js references /static/{name} but nothing serves it (404 fails the precache)"
            );
        }
    }

    /// The other half of the worker's precache: a route, not an asset, so the
    /// scan above cannot see it. Renaming `/offline` without editing the worker
    /// leaves the fallback pointing at a 404.
    #[test]
    fn service_worker_offline_fallback_matches_the_route() {
        assert!(
            SERVICE_WORKER.contains("'/offline'"),
            "sw.js must name the /offline route it falls back to"
        );
    }

    /// The worker's other route reference. `/entries/offline` is the reader's
    /// saved-article library, and the worker answers dead entry-list
    /// navigations with the cached copy of it; renaming the route without
    /// editing the worker turns that fallback into a permanent miss, visible
    /// only as the apology page appearing where the library should be.
    #[test]
    fn service_worker_offline_library_matches_the_route() {
        assert!(
            SERVICE_WORKER.contains("'/entries/offline'"),
            "sw.js must name the /entries/offline route it serves saved articles from"
        );
    }

    /// The third reference to that route, and the only one a reader can click.
    /// `rdrs-sidebar.js` writes its own markup with no Askama counterpart, so a
    /// link dropped from it goes missing silently — and with it every way into
    /// the library, since Load More reaches the server and a list truncated at
    /// the page size is exactly what a reader offline cannot extend.
    #[test]
    fn the_sidebar_offers_the_offline_library() {
        let sidebar = FILES
            .iter()
            .find(|(name, _)| *name == "js/components/rdrs-sidebar.js")
            .expect("the sidebar component is embedded")
            .1;
        assert!(
            sidebar.contains(r#"href="/entries/offline""#),
            "the sidebar must link /entries/offline — nothing else does"
        );
    }

    /// The worker script as it is actually served, placeholders substituted.
    async fn served_worker_body() -> String {
        let resp = service_worker().await;
        let bytes = axum::body::to_bytes(resp.into_body(), usize::MAX)
            .await
            .unwrap();
        String::from_utf8(bytes.to_vec()).unwrap()
    }

    /// `immutable` on a URL that carries no `?v=` would pin one build's worker
    /// forever, and the URL is unstamped on purpose — see [`service_worker`].
    #[tokio::test]
    async fn service_worker_is_version_stamped_but_not_immutable() {
        let resp = service_worker().await;

        assert_eq!(
            resp.headers().get(header::CACHE_CONTROL).unwrap(),
            "no-cache"
        );
        assert_eq!(
            resp.headers().get(header::CONTENT_TYPE).unwrap(),
            "application/javascript"
        );

        let body = served_worker_body().await;

        // The version travels in the body rather than the URL, so this is the
        // only thing that tells a browser a new worker is due.
        assert!(
            !body.contains(ASSET_VERSION_PLACEHOLDER),
            "placeholder was not substituted"
        );
        assert!(
            body.contains(crate::GIT_VERSION),
            "worker body must carry the build version"
        );
    }

    /// The worker's runtime cache must be on exactly when the server is still
    /// marking `/static/` immutable.
    ///
    /// A build from a dirty tree stamps every `?v=` URL identically across
    /// consecutive edits, which is why [`cache_control_for`] drops to
    /// `no-cache` there — and the Cache API honours no such header, so a worker
    /// left caching would hand the stale copy straight back and quietly undo
    /// the escape hatch. Whichever build this test runs on, the two must agree.
    #[tokio::test]
    async fn service_worker_static_cache_tracks_the_asset_cache_control() {
        let body = served_worker_body().await;

        assert!(
            !body.contains(STATIC_CACHE_PLACEHOLDER),
            "placeholder was not substituted"
        );

        let expected = format!("'{}' === 'true'", worker_may_cache_static());
        assert!(
            body.contains(&expected),
            "assets are served `{}`, so the worker should carry `{expected}`",
            cache_control_for()
        );
    }

    /// A manifest that does not parse, or names an icon nothing serves, makes
    /// the app quietly uninstallable — browsers report neither.
    #[tokio::test]
    async fn manifest_parses_and_its_icons_are_servable() {
        let body = body_of("manifest.webmanifest").await;
        assert!(
            !body.contains(ASSET_VERSION_PLACEHOLDER),
            "placeholder was not substituted"
        );

        let manifest: serde_json::Value = serde_json::from_str(&body).unwrap();
        assert_eq!(manifest["start_url"], "/");
        assert_eq!(manifest["scope"], "/");
        assert_eq!(manifest["display"], "standalone");

        let icons = manifest["icons"].as_array().unwrap();
        for icon in icons {
            let src = icon["src"].as_str().unwrap();
            assert!(
                src.contains(&format!("?v={}", crate::GIT_VERSION)),
                "{src} must be version-stamped, or an upgrade cannot replace it"
            );
            let name = static_urls_in(src)
                .pop()
                .unwrap_or_else(|| panic!("{src} is not a /static/ URL"));
            assert!(is_servable(&name), "manifest names /static/{name}, a 404");
        }

        // An installable manifest needs a 192 and a 512 for the `any` purpose,
        // plus a maskable one so Android does not letterbox the icon inside its
        // own mask.
        for expected in ["192x192", "512x512"] {
            assert!(
                icons
                    .iter()
                    .any(|i| i["sizes"] == expected && i["purpose"] == "any"),
                "manifest is missing an `any` icon at {expected}"
            );
        }
        assert!(
            icons.iter().any(|i| i["purpose"] == "maskable"),
            "manifest is missing a maskable icon"
        );
    }

    /// With `nosniff` on every response, a mislabelled manifest or icon is not
    /// a cosmetic problem — the browser rejects it outright.
    #[tokio::test]
    async fn pwa_assets_are_served_under_their_own_content_types() {
        for (path, expected) in [
            ("manifest.webmanifest", "application/manifest+json"),
            ("icons/icon-192.png", "image/png"),
            ("icons/icon-512.png", "image/png"),
            ("icons/maskable-icon-512.png", "image/png"),
        ] {
            let resp = serve(Path(path.to_string())).await;
            assert_eq!(resp.status(), StatusCode::OK, "{path} must be served");
            assert_eq!(
                resp.headers().get(header::CONTENT_TYPE).unwrap(),
                expected,
                "{path} content type"
            );
        }
    }
}
