use axum::{
    extract::Path,
    http::{StatusCode, header},
    response::{IntoResponse, Response},
};

// Embed all static assets at compile time for single-binary deployment
const FILES: &[(&str, &str)] = &[
    ("css/app.css", include_str!("../../static/css/app.css")),
    // Under `/static/` so session/CSRF layers skip it and the public, immutable
    // response is cookie-free; hence `start_url`/`scope` inside must be absolute.
    (
        "manifest.webmanifest",
        include_str!("../../static/manifest.webmanifest"),
    ),
    ("js/app.js", include_str!("../../static/js/app.js")),
    (
        "js/behaviors.js",
        include_str!("../../static/js/behaviors.js"),
    ),
    ("js/admin.js", include_str!("../../static/js/admin.js")),
    ("js/csrf.js", include_str!("../../static/js/csrf.js")),
    ("js/login.js", include_str!("../../static/js/login.js")),
    ("js/passkey.js", include_str!("../../static/js/passkey.js")),
    ("js/offline.js", include_str!("../../static/js/offline.js")),
    ("js/pwa.js", include_str!("../../static/js/pwa.js")),
    ("js/setup.js", include_str!("../../static/js/setup.js")),
    ("js/search.js", include_str!("../../static/js/search.js")),
    (
        "js/statistics.js",
        include_str!("../../static/js/statistics.js"),
    ),
    (
        "js/summarizer.js",
        include_str!("../../static/js/summarizer.js"),
    ),
    ("js/utils.js", include_str!("../../static/js/utils.js")),
    (
        "js/components/rdrs-flash.js",
        include_str!("../../static/js/components/rdrs-flash.js"),
    ),
    (
        "js/components/rdrs-kb-help.js",
        include_str!("../../static/js/components/rdrs-kb-help.js"),
    ),
    (
        "js/components/rdrs-sidebar.js",
        include_str!("../../static/js/components/rdrs-sidebar.js"),
    ),
];

// Self-hosted webfonts (latin subset), vendored to avoid a CDN; SIL OFL, see
// static/fonts/OFL-*.txt.
const FONTS: &[(&str, &[u8])] = &[
    (
        "fonts/newsreader-latin.woff2",
        include_bytes!("../../static/fonts/newsreader-latin.woff2"),
    ),
    (
        "fonts/newsreader-italic-latin.woff2",
        include_bytes!("../../static/fonts/newsreader-italic-latin.woff2"),
    ),
    (
        "fonts/archivo-latin.woff2",
        include_bytes!("../../static/fonts/archivo-latin.woff2"),
    ),
    (
        "fonts/ibm-plex-mono-400-latin.woff2",
        include_bytes!("../../static/fonts/ibm-plex-mono-400-latin.woff2"),
    ),
    (
        "fonts/ibm-plex-mono-500-latin.woff2",
        include_bytes!("../../static/fonts/ibm-plex-mono-500-latin.woff2"),
    ),
    (
        "fonts/ibm-plex-mono-600-latin.woff2",
        include_bytes!("../../static/fonts/ibm-plex-mono-600-latin.woff2"),
    ),
    (
        "fonts/noto-sans-symbols2-stars.woff2",
        include_bytes!("../../static/fonts/noto-sans-symbols2-stars.woff2"),
    ),
];

// Manifest icons, generated by `build.rs` from `favicon.svg`. Served under
// `/static/` (not with the favicons) so middleware skip lists already cover them.
const ICONS: &[(&str, &[u8])] = &[
    (
        "icons/icon-192.png",
        include_bytes!(concat!(env!("OUT_DIR"), "/icon-192.png")),
    ),
    (
        "icons/icon-512.png",
        include_bytes!(concat!(env!("OUT_DIR"), "/icon-512.png")),
    ),
    (
        "icons/maskable-icon-512.png",
        include_bytes!(concat!(env!("OUT_DIR"), "/maskable-icon-512.png")),
    ),
];

/// Served from the site root by [`service_worker`], not via [`FILES`], so its
/// scope covers the whole site.
const SERVICE_WORKER: &str = include_str!("../../static/js/sw.js");

/// Replaced at serve time with the build version so nested ES-module imports get
/// `?v=`-stamped URLs; bare URLs would be cached forever under `immutable`.
const ASSET_VERSION_PLACEHOLDER: &str = "__RDRS_ASSET_VERSION__";

/// Replaced in the service worker with [`worker_may_cache_static`]'s answer.
const STATIC_CACHE_PLACEHOLDER: &str = "__RDRS_CACHE_STATIC__";

/// Whether the service worker may cache `/static/` responses. Derived from
/// [`cache_control_for`] since the Cache API ignores `Cache-Control`.
fn worker_may_cache_static() -> bool {
    cache_control_for() != "no-cache"
}

fn content_type_for(path: &str) -> &'static str {
    match std::path::Path::new(path)
        .extension()
        .and_then(|ext| ext.to_str())
    {
        Some("css") => "text/css; charset=utf-8",
        Some("woff2") => "font/woff2",
        Some("png") => "image/png",
        // Under `nosniff`, a mislabelled manifest is rejected outright.
        Some("webmanifest") => "application/manifest+json",
        _ => "application/javascript",
    }
}

/// Shared with `handlers::favicon`.
pub(crate) fn cache_control_for() -> &'static str {
    // A `-dirty` version is identical across dev edits, so `immutable` would
    // serve stale assets.
    if crate::GIT_VERSION.ends_with("-dirty") {
        "no-cache"
    } else {
        "public, max-age=31536000, immutable"
    }
}

/// `GET /sw.js`. Unstamped URL (a stamped one would register a new worker each
/// deploy), so it must be `no-cache`, never `immutable`.
pub async fn service_worker() -> Response {
    (
        StatusCode::OK,
        [
            (header::CONTENT_TYPE, "application/javascript"),
            (header::CACHE_CONTROL, "no-cache"),
        ],
        SERVICE_WORKER
            .replace(ASSET_VERSION_PLACEHOLDER, crate::GIT_VERSION)
            .replace(
                STATIC_CACHE_PLACEHOLDER,
                if worker_may_cache_static() {
                    "true"
                } else {
                    "false"
                },
            ),
    )
        .into_response()
}

pub async fn serve(Path(path): Path<String>) -> Response {
    if let Some((name, bytes)) = FONTS.iter().chain(ICONS).find(|(name, _)| *name == path) {
        return (
            StatusCode::OK,
            [
                (header::CONTENT_TYPE, content_type_for(name)),
                (header::CACHE_CONTROL, cache_control_for()),
            ],
            *bytes,
        )
            .into_response();
    }
    match FILES.iter().find(|(name, _)| *name == path) {
        Some((name, content)) => (
            StatusCode::OK,
            [
                (header::CONTENT_TYPE, content_type_for(name)),
                (header::CACHE_CONTROL, cache_control_for()),
            ],
            content.replace(ASSET_VERSION_PLACEHOLDER, crate::GIT_VERSION),
        )
            .into_response(),
        None => StatusCode::NOT_FOUND.into_response(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every `/static/…` URL in `source` as a serve-table key (prefix and `?v=`
    /// dropped); a bare prefix yields nothing.
    fn static_urls_in(source: &str) -> Vec<String> {
        source
            .match_indices("/static/")
            .map(|(i, _)| {
                source[i + "/static/".len()..]
                    .chars()
                    .take_while(|c| !matches!(c, '"' | '\'' | '`' | '?' | ' ' | '>' | '\n'))
                    .collect::<String>()
            })
            .filter(|name: &String| !name.is_empty())
            .collect()
    }

    fn is_servable(name: &str) -> bool {
        FILES.iter().any(|(n, _)| *n == name) || FONTS.iter().chain(ICONS).any(|(n, _)| *n == name)
    }

    async fn body_of(path: &str) -> String {
        let resp = serve(Path(path.to_string())).await;
        let bytes = axum::body::to_bytes(resp.into_response().into_body(), usize::MAX)
            .await
            .unwrap();
        String::from_utf8(bytes.to_vec()).unwrap()
    }

    /// Importers of `utils.js` must use a version-stamped URL, or `immutable`
    /// keeps a stale copy across deploys.
    #[tokio::test]
    async fn js_nested_imports_are_version_busted() {
        let expected = format!("utils.js?v={}", crate::GIT_VERSION);
        for path in [
            "js/app.js",
            "js/components/rdrs-sidebar.js",
            "js/passkey.js",
        ] {
            let body = body_of(path).await;
            assert!(
                !body.contains(ASSET_VERSION_PLACEHOLDER),
                "{path}: placeholder was not substituted"
            );
            assert!(
                body.contains(&expected),
                "{path}: expected a version-stamped utils.js import ({expected})"
            );
            assert!(
                !body.contains("utils.js'") && !body.contains("utils.js\""),
                "{path}: still imports utils.js without a ?v= cache-buster"
            );
        }
    }

    /// Every `/static/js/*.js` a template references must be in `FILES`, or it
    /// 404s (e.g. a missing `csrf.js` breaks every token-bearing POST).
    #[tokio::test]
    async fn every_template_referenced_script_is_served() {
        let root = concat!(env!("CARGO_MANIFEST_DIR"), "/templates");
        let mut stack = vec![std::path::PathBuf::from(root)];
        let mut refs: Vec<String> = Vec::new();
        while let Some(dir) = stack.pop() {
            for entry in std::fs::read_dir(&dir).unwrap() {
                let path = entry.unwrap().path();
                if path.is_dir() {
                    stack.push(path);
                    continue;
                }
                let html = std::fs::read_to_string(&path).unwrap();
                for (i, _) in html.match_indices("/static/js/") {
                    let tail = &html[i + "/static/".len()..];
                    let name: String = tail
                        .chars()
                        .take_while(|c| !matches!(c, '"' | '\'' | '?' | ' ' | '>' | '\n'))
                        .collect();
                    if std::path::Path::new(&name)
                        .extension()
                        .and_then(|e| e.to_str())
                        == Some("js")
                    {
                        refs.push(name);
                    }
                }
            }
        }
        assert!(
            refs.iter().any(|r| r == "js/csrf.js"),
            "sanity: expected to find at least the csrf.js reference while scanning templates"
        );
        for name in &refs {
            assert!(
                FILES.iter().any(|(n, _)| n == name),
                "template references /static/{name} but it is not registered in FILES (404)"
            );
        }
    }

    /// The precache `addAll` is all-or-nothing; one 404 silently loses the
    /// offline page.
    #[test]
    fn service_worker_only_names_servable_static_urls() {
        let referenced = static_urls_in(SERVICE_WORKER);
        assert!(
            !referenced.is_empty(),
            "sanity: the worker is expected to name at least one static asset"
        );
        for name in &referenced {
            assert!(
                is_servable(name),
                "sw.js references /static/{name} but nothing serves it (404 fails the precache)"
            );
        }
    }

    /// A route, not an asset, so the scan above misses it.
    #[test]
    fn service_worker_offline_fallback_matches_the_route() {
        assert!(
            SERVICE_WORKER.contains("'/offline'"),
            "sw.js must name the /offline route it falls back to"
        );
    }

    /// The worker falls back to the saved-article library for dead entry-list
    /// navigations.
    #[test]
    fn service_worker_offline_library_matches_the_route() {
        assert!(
            SERVICE_WORKER.contains("'/entries/offline'"),
            "sw.js must name the /entries/offline route it serves saved articles from"
        );
    }

    /// The sidebar's link is the only clickable way into the offline library.
    #[test]
    fn the_sidebar_offers_the_offline_library() {
        let sidebar = FILES
            .iter()
            .find(|(name, _)| *name == "js/components/rdrs-sidebar.js")
            .expect("the sidebar component is embedded")
            .1;
        assert!(
            sidebar.contains(r#"href="/entries/offline""#),
            "the sidebar must link /entries/offline — nothing else does"
        );
    }

    async fn served_worker_body() -> String {
        let resp = service_worker().await;
        let bytes = axum::body::to_bytes(resp.into_body(), usize::MAX)
            .await
            .unwrap();
        String::from_utf8(bytes.to_vec()).unwrap()
    }

    /// `immutable` on the unstamped URL would pin one worker forever.
    #[tokio::test]
    async fn service_worker_is_version_stamped_but_not_immutable() {
        let resp = service_worker().await;

        assert_eq!(
            resp.headers().get(header::CACHE_CONTROL).unwrap(),
            "no-cache"
        );
        assert_eq!(
            resp.headers().get(header::CONTENT_TYPE).unwrap(),
            "application/javascript"
        );

        let body = served_worker_body().await;

        // The body version is what signals a new worker.
        assert!(
            !body.contains(ASSET_VERSION_PLACEHOLDER),
            "placeholder was not substituted"
        );
        assert!(
            body.contains(crate::GIT_VERSION),
            "worker body must carry the build version"
        );
    }

    /// The worker's runtime cache must be on exactly when `/static/` is
    /// immutable.
    #[tokio::test]
    async fn service_worker_static_cache_tracks_the_asset_cache_control() {
        let body = served_worker_body().await;

        assert!(
            !body.contains(STATIC_CACHE_PLACEHOLDER),
            "placeholder was not substituted"
        );

        let expected = format!("'{}' === 'true'", worker_may_cache_static());
        assert!(
            body.contains(&expected),
            "assets are served `{}`, so the worker should carry `{expected}`",
            cache_control_for()
        );
    }

    /// A broken manifest or icon makes the app silently uninstallable.
    #[tokio::test]
    async fn manifest_parses_and_its_icons_are_servable() {
        let body = body_of("manifest.webmanifest").await;
        assert!(
            !body.contains(ASSET_VERSION_PLACEHOLDER),
            "placeholder was not substituted"
        );

        let manifest: serde_json::Value = serde_json::from_str(&body).unwrap();
        assert_eq!(manifest["start_url"], "/");
        assert_eq!(manifest["scope"], "/");
        assert_eq!(manifest["display"], "standalone");

        let icons = manifest["icons"].as_array().unwrap();
        for icon in icons {
            let src = icon["src"].as_str().unwrap();
            assert!(
                src.contains(&format!("?v={}", crate::GIT_VERSION)),
                "{src} must be version-stamped, or an upgrade cannot replace it"
            );
            let name = static_urls_in(src)
                .pop()
                .unwrap_or_else(|| panic!("{src} is not a /static/ URL"));
            assert!(is_servable(&name), "manifest names /static/{name}, a 404");
        }

        // Installability needs 192/512 `any` icons, plus a maskable one.
        for expected in ["192x192", "512x512"] {
            assert!(
                icons
                    .iter()
                    .any(|i| i["sizes"] == expected && i["purpose"] == "any"),
                "manifest is missing an `any` icon at {expected}"
            );
        }
        assert!(
            icons.iter().any(|i| i["purpose"] == "maskable"),
            "manifest is missing a maskable icon"
        );
    }

    /// Under `nosniff`, a mislabelled type is rejected outright.
    #[tokio::test]
    async fn pwa_assets_are_served_under_their_own_content_types() {
        for (path, expected) in [
            ("manifest.webmanifest", "application/manifest+json"),
            ("icons/icon-192.png", "image/png"),
            ("icons/icon-512.png", "image/png"),
            ("icons/maskable-icon-512.png", "image/png"),
        ] {
            let resp = serve(Path(path.to_string())).await;
            assert_eq!(resp.status(), StatusCode::OK, "{path} must be served");
            assert_eq!(
                resp.headers().get(header::CONTENT_TYPE).unwrap(),
                expected,
                "{path} content type"
            );
        }
    }
}
